### ISSUE TITLE
Can not connect to camera.

### ISSUE THREAD

**Issue by ducpt2** [Michaelvilleneuve/react-native-document-scanner#10]
I try to build app with react-native-document-scanner, use sample code. But when i run on device, my app can not connect to camera. It only show button Flash, text at bottom and all white screen(can't connect to camera). 
someone know to fix it? Many thanks.

**Comment by Michaelvilleneuve** [comment]
Hi, are you running the demo on an actual device ? Camera does not work on simulator. Also have you ran react-native link ?

**Comment by ducpt2** [comment]
@Michaelvilleneuve Yes, i'm sure that i run on real device, and run react-native link. I think something is broken in your bridge code.

**Comment by Michaelvilleneuve** [comment]
Can you try changing data.image to data.croppedImage in index.ios.js.
I think that I forgot to update the example project.

**Comment by Michaelvilleneuve** [comment]
Ok I just tested successfully the example project. I just published a fix regarding an issue in the example project with react dependency and regarding the above comment. Aside from that it was working just as expected.

Please provide more detail. Are you sure you are running the project with an iPhone?

**Comment by ducpt2** [comment]
I just try to run your Example, and it work. 
Thank you Michaelvilleneuve.
I hope you can make a quick video to setup your two awsome library as well.Thanks.

**Comment by Michaelvilleneuve** [comment]
Cool :). I'll try to integrate the cropper library as well to the example project this week. I'll just make a shell script that will automate the process, I guess it will be simpler

**Comment by ducpt2** [comment]
Hi Michaelvilleneuve,

I ran your lib in ReactNative-iOS project and it work perfectly,
so I provide you some native android scan document library, hope you can
make your libe work with android too.

Thank you so much.

2017-10-03 13:58 GMT+07:00 Michaël Villeneuve <notifications@github.com>:
