### ISSUE TITLE
Build Failed... issue with RCTBridgeModule

### ISSUE THREAD

**Issue by CharlieOrlando** [Michaelvilleneuve/react-native-document-scanner#12]
This package worked perfectly on my last project (react-native 0.44.0 and react-native-document-scanner ^1.2.1), but I'm getting a build error on my new project (react-native 0.49.1 and react-native-document-scanner 1.3.0). I've tried downgrading the document-scanner to 1.2.1, but it throws the same error...

![documentscannererror](https://user-images.githubusercontent.com/25595536/31408061-d5081086-adcc-11e7-9c99-0e0a93e6e936.png)

I then tried uninstalling the package and unlinking, but my project still wont build. I get an Apple Mach-O Linker Error, which says 

"ld: library not found for -lRNPdfScanner
clang: error: linker command failed with exit code 1 (use -v to see invocation)"

Can't seem to resolve either error.

Edit... 
List of solutions I've tried so far:
- Reinstalling/relinking package
- Downgrading package
- Clearing derived data
- Cleaning project then rebuilding

Wondering if I may have to downgrade react native itself

**Comment by CharlieOrlando** [comment]
Update... I've finally fixed the error by changing the code in ios/RNPdfScannerManager.h

from this:

`#if __has_include("RCTBridgeModule.h")
#import "RCTBridgeModule.h"
#else
#import <React/RCTBridgeModule.h>
#endif

#if __has_include(<React/RCTViewManager.h>)
#import <React/RCTViewManager.h>
#elif __has_include("RCTViewManager.h")
#import "RCTViewManager.h"
#else
#import "React/RCTViewManager.h"
#endif`

to:

`#import <React/RCTBridgeModule.h>

#import <React/RCTViewManager.h>`

**Comment by Michaelvilleneuve** [comment]
Hey ! I've seen someone using this fix to make it work on React Native 0.48+, I think I'll post an update as it seems to be the go to solution now.
