### ISSUE TITLE
Can not run on iOS devices with Xcode9.

### ISSUE THREAD

**Issue by mafang99** [Michaelvilleneuve/react-native-document-scanner#13]
Showing All Messages xxxxxx/node_modules/react-native/React/Base/RCTBridgeModule.h:54:16: Redefinition of 'RCTMethodInfo'

Showing All Messages
xxxxxx/node_modules/react-native-document-scanner/ios/RNPdfScannerManager.m:2:9: In file included from xxxxxx/node_modules/react-native-document-scanner/ios/RNPdfScannerManager.m:2:

xxxxxx/node_modules/react-native-document-scanner/ios/RNPdfScannerManager.h:9:9: In file included from xxxxxx/node_modules/react-native-document-scanner/ios/RNPdfScannerManager.h:9:

I use reactive-native 0.48.3. and try run on iOS Devices. Then xcode9 shows build failed with these info.

**Comment by Michaelvilleneuve** [comment]
Hello, please use this fix, I'll post an update soon. Feel free to submit a PR a it works ! https://github.com/Michaelvilleneuve/react-native-document-scanner/issues/12

**Comment by andres-ortiz** [comment]
You can close Issue !
