### ISSUE TITLE
Change image quality?

### ISSUE THREAD

**Issue by CharlieOrlando** [Michaelvilleneuve/react-native-document-scanner#2]
Hey! You did an excellent job with this, and it works amazingly well, but I'm wondering if you're planning to add the ability to change the image quality. Currently, the images end up being exceedingly large (10+mb).

**Comment by Michaelvilleneuve** [comment]
Hi ! Seriously, 10mb ?? I have not been using the images outside of the app so I have not noticed their size. I'll see if I can add it this week.

In the meantime I am sure you can manage to do it in pure JS if you need to 😊

**Comment by CharlieOrlando** [comment]
Yeah. I tried uploading the base64 string to firebase, but got an error that said I had exceeded the maximum size (of 10mb). The error doesn't occur if I scan the document from further away.

I've been looking into workarounds, and I think I can solve the issue. I appreciate the quick response, though! Please lemme know if you come up with any solutions

**Comment by Michaelvilleneuve** [comment]
Hey ! Fixed in f53cdcb600a8f181d816f04b16986aec7ef3a99f
Image is now encoded in JPEG and I also added option for quality on the component itself.
Hope this helps !

**Comment by CharlieOrlando** [comment]
Damn. Thanks for addressing the issue so quickly
