### ISSUE TITLE
Invariant Violation: Native component for "RNPdfScanner" does not exist

### ISSUE THREAD

**Issue by nic-lan** [Michaelvilleneuve/react-native-document-scanner#22]
Hello, it looks like the index.js is not able to load the the RNPdfScanner even if i see 
```
Invariant Violation: Native component for "RNPdfScanner" does not exist

This error is located at:
    in RNPdfScanner (at index.js:33)
    in PdfScanner (at WScanner.js:27)
    in WScanner (at App.js:21)
    in App (at registerRootComponent.js:34)
    in RootErrorBoundary (at registerRootComponent.js:33)
    in ExpoRootComponent (at renderApplication.js:35)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:34)
```

i see the explicit require on line 5 though
```
const RNPdfScanner = requireNativeComponent('RNPdfScanner', PdfScanner);
```

npm 5.5.1
node 9.0.0
expo xde on top

**Comment by Michaelvilleneuve** [comment]
Hey, you need to link the library. This lib is not compatible with expo though.

**Comment by kennethkloeppel** [comment]
I attempted to install this today and am getting the same error.  After the install I issued the link command and it appears to have linked.  I'm a bit green when it comes to some of these linked libraries.  

$ react-native link react-native-document-scanner
Scanning folders for symlinks in /*******/node_modules (18ms)
rnpm-install info Linking react-native-document-scanner android dependency 
rnpm-install info Android module react-native-document-scanner has been successfully linked 
rnpm-install info Linking react-native-document-scanner ios dependency 
rnpm-install info iOS module react-native-document-scanner has been successfully linked

**Comment by Michaelvilleneuve** [comment]
Have you recompiled you app after linking ?

**Comment by kennethkloeppel** [comment]
You're right.  I didn't.  I told you... newbie here.  LOL  

Thanks!

**Comment by vinitty** [comment]
can i use this library with expo , or is there any library like this which has support in expo
