### ISSUE TITLE
How to get working on a new project?

### ISSUE THREAD

**Issue by reForMatt** [Michaelvilleneuve/react-native-document-scanner#29]
This library looks perfect for a new project I'm working on, but I'm struggling to get it working with a fresh create-react-native-app. I'm pretty new to React-Native, how should I get this library to work on my app? Should I start the react-native app a different way?

Thanks a lot!

**Comment by Michaelvilleneuve** [comment]
Hi, this lib is not expo compatible, meaning you need to either eject from create-react-native-app or recreate your app using `react-native init`. The process is pretty well documented here https://facebook.github.io/react-native/docs/getting-started.html under the tab 'project with native code'
