### ISSUE TITLE
Change the quality of image

### ISSUE THREAD

**Issue by vosamoilenko** [Michaelvilleneuve/react-native-document-scanner#3]
I get an image with 2,2 MB, is there any options to change a quality?

**Comment by Michaelvilleneuve** [comment]
Have you try the quality prop ? Available in latest version.

**Comment by vosamoilenko** [comment]
Are you sure that it works correctly?
I get a difference on which distance I make a photo. I got 10 MB when a camera was very near to document when it's away from a document the size of photo near 2 MB. But I don't see any dependence to prop 'quality'.


```
<DocumentScanner
      onPictureTaken={
        (data) => {
          this.props.nextScreen(data.image);
        }
      }
      overlayColor="rgba(236,151,109, 0.7)"
      enableTorch={false}
      brightness={0}
      quality={0.3} // doesn't work
      saturation={1}
      contrast={1}
      onRectangleDetect={
        ({ stableCounter, lastDetectionType }) =>
          this.setState({ stableCounter, lastDetectionType })}
      detectionCountBeforeCapture={5}
      detectionRefreshRateInMS={50}
      style={{ flex: 1 }}
    />
```

**Comment by Michaelvilleneuve** [comment]
I have been getting results as low as 0.2mb with decent quality. Are you using version v1.1.2 ? 
If you are not sure could you please try uninstalling the lib and then specifying "react-native-document-scanner": "1.1.2" in your package.json ?

**Comment by vosamoilenko** [comment]
Yeap, a problem was with packages. Thanks, the library is great
