### ISSUE TITLE
Example isn't up-to-date

### ISSUE THREAD

**Issue by zedtux** [Michaelvilleneuve/react-native-document-scanner#31]
The example from this repo seem to use a different version of the actual version of this package (using `<Scanner ... />` instead of `<DocumentScanner ... />`.

I guess it has been made with an older version of this library.

Could you please update it ?

**Comment by Michaelvilleneuve** [comment]
Considering that the main component is exported as default, you can actually name it the way you want it as long as you import it from the right package..

**Comment by zedtux** [comment]
Oh ... I see. Thank you @Michaelvilleneuve and sorry for the noise ... 😞

**Comment by Michaelvilleneuve** [comment]
No problem @zedtux ! :)
