### ISSUE TITLE
Instructions to run the Example app

### ISSUE THREAD

**Issue by SrujithPoondla** [Michaelvilleneuve/react-native-document-scanner#32]
These are the steps i followed to run the Example app.

1. git clone https://github.com/Michaelvilleneuve/react-native-document-scanner.git
2. cd react-native-documrnt-scanner/Example
3. npm install
4. react-native run-ios

This is the error i am getting 

```
error: bundling: UnableToResolveError: Unable to resolve module `react` from `/Users/srujithpoondla/react-native-document-scanner/index.js`: Module does not exist in the module map or in these directories:
  /Users/srujithpoondla/node_modules
```
But react module is available in node_modules. 
Are there any specific instructions to run the example app? 

Thanks!

**Comment by Michaelvilleneuve** [comment]
The steps you followed seem correct. Try to uninstall react from your node_modules and install it again ?

**Comment by SrujithPoondla** [comment]
I tried uninstalling all the node modules and reinstalling. It didn’t work. Any other suggestions?

Now i am trying to use directly in an app. After using react native link, still do i need to add camera to the permissions in xcode and android?

**Comment by Michaelvilleneuve** [comment]
Unfortunately I don't have time to maintain this package anymore. I am just trying to help whenever I can.

Feel free to submit PRs and I will look into it
