### ISSUE TITLE
Pass URI instead of base64

### ISSUE THREAD

**Issue by poyannabati** [Michaelvilleneuve/react-native-document-scanner#4]
I think it should be optional to pass the base64 encoded data and by default pass the URI. This would avoid an, unnecessary, large transfer over the bridge.

**Comment by Michaelvilleneuve** [comment]
Hi, I didn't need it but yeah it would be great. I've seen you started working on it, feel free to PR

**Comment by poyannabati** [comment]
⭐️

**Comment by poyannabati** [comment]
I did start but started wondering: there seems to be more things that differ in the latest version of the underlying lib. Any 'rebasing' this project off of the latest version?

**Comment by Michaelvilleneuve** [comment]
If you are talking about that  lib https://github.com/mmackh/IPDFCameraViewController 
It has not been updated since 11 month. Where have you found changes ?

**Comment by poyannabati** [comment]
I think the default behaviour should be to pass the URI rather than the base64, what do you think @Michaelvilleneuve ?

**Comment by Michaelvilleneuve** [comment]
Yes I agree, I needed base64 only for my project but of course it bottlenecks the JS bridge and adds some MS to the response time. Plus it forces you to deal with other JS libraries if you need to save it elsewhere.. 
I really don't have time to work on it right now but I would be more than happy to merge this feature !
