### ISSUE TITLE
How to work manual capture

### ISSUE THREAD

**Issue by vincentgheza** [Michaelvilleneuve/react-native-document-scanner#51]
Hi, first thank for your work.
But i have a little problem with manual capture , i cannot understand how to work , and how to retrieve data as onPictureTaken.

Could you explain the difference please ?
Thx.

**Comment by Michaelvilleneuve** [comment]
To do manual capture you need to get the ref of your component ref={ref => this.scanner = ref}

Then whenever you want to capture you just call this.scanner.capture()

No matter the way you captured the image (auto or manual) you will receive the result in the onPictureTaken method

**Comment by vincentgheza** [comment]
Ok thank you, with the version 1.4.0 the manuel method is working also ?
