### ISSUE TITLE
Only one image capture is allowed

### ISSUE THREAD

**Issue by poyannabati** [Michaelvilleneuve/react-native-document-scanner#6]
Unless you unmount the DocumentScanner component (for instance while showing a review screen), you can't continue taking photos but you are met with a blank screen. Camera view disappears.

**Comment by Michaelvilleneuve** [comment]
Yes indeed. But I don't see in which cases you would want to keep the camera active even though you've taken a picture ?  Is it for performance concerns ?

**Comment by poyannabati** [comment]
@Michaelvilleneuve basically, auto-capture mode (scanning multiple pages without approving each one).

**Comment by Michaelvilleneuve** [comment]
Oh I see, would be a cool feature indeed. 

I can't work on it right now, I'm working on a custom crop system which would be a great addition to this library : 

![img_1026 - copie](https://user-images.githubusercontent.com/4990201/29470925-7cdee92c-844e-11e7-9720-432cf1d3f173.png)

But I'm pretty sure it would work out of the box if you just remove `[self stop];` from `DocumentScannerView.m`
