### ISSUE TITLE
IOS 13 Some crash or blank/White screen after capture

### ISSUE THREAD

**Issue by vdebruyn** [Michaelvilleneuve/react-native-document-scanner#66]
Hello, 

Hello,
With IOS 13, I have several problems.

Crashes of the application without having report of errors and especially a screen which remains white after the capture.

At the debug level, during capture, nothing happens, reactotron does not even return the cropped image and infomation.

So if you had an idea of ​​the causes.

RN 0.38.1 and i try different version of module.

**Comment by joaonew** [comment]
Were you able to make it work?
