### ISSUE TITLE
RNPdfScanner" does not exist

### ISSUE THREAD

**Issue by isaacboratino** [Michaelvilleneuve/react-native-document-scanner#7]
On androi i get error

index.android.bundle?platform=android&dev=true&hot=true&minify=true:357 Warning: Native component for "RNPdfScanner" does not exist
t @ index.android.bundle?platform=android&dev=true&hot=true&minify=true:357

**Comment by Michaelvilleneuve** [comment]
Hi, Document Scanner is not available on Android for now, please add a condition like that : 
```javascript
if (Platform.OS === 'ios') {
   <DocumentScanner ... />
}
```
