### ISSUE TITLE
Any chance for an option to save an actual file?

### ISSUE THREAD

**Issue by CharlieOrlando** [Michaelvilleneuve/react-native-document-scanner#8]
Instead of the base64. Aside from that, the scanner is perfect and the new image cropper is also great

**Comment by Michaelvilleneuve** [comment]
I'm on holiday until September 5th, but it is #1 on the todo for when I get back 👍🏼

**Comment by CharlieOrlando** [comment]
Awesome! Appreciate the speedy reply. Enjoy the holiday!

**Comment by Michaelvilleneuve** [comment]
Hello ! Sorry for the false hope. Unfortunatly I’ve been working on completely different projects since september and I have not taken time to add this feature ☹️

**Comment by CharlieOrlando** [comment]
No worries at all!

**Comment by CharlieOrlando** [comment]
Hate to bother you, but I'm kinda at a loss for what to do. The document scanner worked perfectly on my last project, but I just installed it on my current one, and it wouldn't build. I then uninstalled it and unlinked, and now my project wont build at all. 

Getting an Apple Mach-O Linker Error, saying
"ld: library not found for -lRNPdfScanner
clang: error: linker command failed with exit code 1 (use -v to see invocation)"

Been frantically looking for a solution for the past hour, but there doesn't seem to be any answer. Wondering if you have any idea why this would be occurring??

**Comment by CharlieOrlando** [comment]
The previous project was using document scanner ^1.2.1. This new one is using document scanner ^1.3.0. Gonna try downgrading and then report back

**Comment by Michaelvilleneuve** [comment]
Hey ! Regarding your initial issue https://github.com/Michaelvilleneuve/react-native-document-scanner/commit/4b8a6627cf77f6969d8c97d95750d4cf572cce76

**Comment by CharlieOrlando** [comment]
Awesome! Appreciate you taking the time to do this

**Comment by Michaelvilleneuve** [comment]
Don’t thank me I just merged it ;) https://github.com/Michaelvilleneuve/react-native-document-scanner/commit/4dfce4d9968b7d4f30be928c9de70d5e9a1137b9
